version: "3.8"

services:
  weather-app:
    container_name: weather-app
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "4000:80"
